### ISSUE TITLE
`GzipDecoder` panics with "Write after end of stream" on bad data

### ISSUE THREAD

**Issue by tgnottingham** [Nullus157/async-compression#188]
The following program panics inside of `async-compression`:

```rust
use tokio::io::AsyncWriteExt;

#[tokio::main]
async fn main() {
    let s = "a";

    let mut enc = async_compression::tokio::write::GzipEncoder::new(Vec::new());
    enc.write_all(s.as_bytes()).await.unwrap();
    enc.shutdown().await.unwrap();
    let v = enc.into_inner();

    let mut v2 = Vec::<u8>::new();
    v2.extend(&v);
    v2.extend(&v);

    let mut dec = async_compression::tokio::write::GzipDecoder::new(Vec::new());
    dec.write_all(&v2).await.unwrap();
    dec.shutdown().await.unwrap();
    let _ = dec.into_inner();
}
```
Backtrace:

```
thread 'main' panicked at 'Write after end of stream', /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-compression-0.3.15/src/tokio/write/generic/decoder.rs:86:32
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:607:12
   1: async_compression::tokio::write::generic::decoder::Decoder<W,D>::do_poll_write
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-compression-0.3.15/src/tokio/write/generic/decoder.rs:86:32
   2: <async_compression::tokio::write::generic::decoder::Decoder<W,D> as tokio::io::async_write::AsyncWrite>::poll_write
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-compression-0.3.15/src/tokio/write/generic/decoder.rs:146:15
   3: <async_compression::tokio::write::GzipDecoder<W> as tokio::io::async_write::AsyncWrite>::poll_write
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-compression-0.3.15/src/tokio/write/macros/decoder.rs:62:17
   4: <&mut T as tokio::io::async_write::AsyncWrite>::poll_write
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/io/async_write.rs:192:13
   5: <tokio::io::util::write_all::WriteAll<W> as core::future::future::Future>::poll
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/io/util/write_all.rs:43:28
   6: use_async_compression::main::{{closure}}
             at ./src/main.rs:17:23
   7: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:63
   8: tokio::runtime::coop::with_budget
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
  10: tokio::runtime::park::CachedParkThread::block_on
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:31
  11: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/context.rs:315:13
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  13: tokio::runtime::runtime::Runtime::block_on
             at /home/tgnottingham/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/runtime.rs:304:45
  14: use_async_compression::main
             at ./src/main.rs:19:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The example is contrived of course. The original use case is decoding untrusted data, where we can't know ahead of time that the data is invalid.

**Comment by Nemo157** [comment]
Thinking about this situation a bit more, I think that panic is incorrect, the writer should just start rejecting new data by returning `Ready(Ok(0))`. This would then cause a panic in the provided example at the `write_all().unwrap()` because of a `WriteZero` error return, but for code that wants to handle this they can see that error and do something about it. There could also be a `multiple_members` flag on the writer similar to the reader structs that will reset the state and expect a new compressed member to be written after the previous completed.

**Comment by abernix** [comment]
@tgnottingham In case you missed it, https://github.com/Nullus157/async-compression/pull/255 recently was merged and claims to help with this issue.  I'm curious if you think that fix will allow this to be resolved?  (Do you want to try it out before it's released?)

**Comment by tgnottingham** [comment]
Hi @abernix, I tested the fix out, and it resolves the issue for me. Thanks for the ping! I'll close this.

(By the way, I interviewed with you at Apollo a couple of years ago. The Rust world is a small one!)
